### ISSUE TITLE
Problems testing InterpreterExecutionBatch in RDFExport branch

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#117]
When trying to test branch RDFExport, when running InterpreterExecutionBatch (with proper configs pointing to config and to a folder with one csv file), I got: 

```
.09:52:15.613 [main] INFO  c.c.m.x.o.t.e.TableMinerPlusFactory - Initializing LEARNING components ... 
.09:52:15.624 [main] INFO  c.c.m.x.o.t.e.TableMinerPlusFactory - Initializing UPDATE components ... 
.09:52:15.626 [main] INFO  c.c.m.x.o.t.e.TableMinerPlusFactory - Initializing RELATIONLEARNING components ... 
Result - Error:
log4j:WARN No appenders could be found for logger (uk.ac.shef.dcs.sti.core.algorithm.tmp.TMPInterpreter).
End of result.
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
uk.ac.shef.dcs.sti.STIException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at uk.ac.shef.dcs.sti.core.algorithm.tmp.TMPInterpreter.start(TMPInterpreter.java:106)
	at cz.cuni.mff.xrg.odalic.tasks.executions.InterpreterExecutionBatch.main(InterpreterExecutionBatch.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at uk.ac.shef.dcs.sti.core.subjectcol.TColumnFeatureGenerator.setMostFrequentDataTypes(TColumnFeatureGenerator.java:128)
	at uk.ac.shef.dcs.sti.core.subjectcol.SubjectColumnDetector.compute(SubjectColumnDetector.java:82)
	at uk.ac.shef.dcs.sti.core.algorithm.tmp.TMPInterpreter.start(TMPInterpreter.java:60)
	... 6 more

```

**Comment by tomas-knap** [comment]
Solved
