### ISSUE TITLE
Core algorithm - problem processing books-v4 file - no result

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#156]
Tested on develop branch from (7.9.). Tested on file: 
[Books-v4.csv.zip](https://github.com/odalic/sti/files/463553/Books-v4.csv.zip)
Empty cache to start with. 

Steps: Just upload the file, run execution. At the end it returns empty page (as task result) and in the log there is (at the end): 

```
.0 sec paused) to merge segment [0.09 MB, 1.04 MB/sec] 
.10:27:03.770 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [IW][Lucene Merge Thread #0]: merged segment size=0.092 MB vs estimate=0.137 MB 
.10:27:03.770 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [IW][Lucene Merge Thread #0]: commitMerge: _8c(5.5.1):C271/4:delGen=4 _8h(5.5.1):C1 _8l(5.5.1):C1 _8k(5.5.1):C1 _8j(5.5.1):C1 _8i(5.5.1):C1 _8g(5.5.1):C1 _8e(5.5.1):C1 _8f(5.5.1):C1 _8d(5.5.1):C1 index=_8c(5.5.1):C271/4:delGen=4 _8d(5.5.1):C1 _8e(5.5.1):C1 _8f(5.5.1):C1 _8g(5.5.1):C1 _8h(5.5.1):C1 _8i(5.5.1):C1 _8j(5.5.1):C1 _8k(5.5.1):C1 _8l(5.5.1):C1 
.10:27:03.770 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [IW][Lucene Merge Thread #0]: commitMergeDeletes _8c(5.5.1):C271/4:delGen=4 _8h(5.5.1):C1 _8l(5.5.1):C1 _8k(5.5.1):C1 _8j(5.5.1):C1 _8i(5.5.1):C1 _8g(5.5.1):C1 _8e(5.5.1):C1 _8f(5.5.1):C1 _8d(5.5.1):C1 
.10:27:03.771 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [IW][Lucene Merge Thread #0]: no new deletes or field updates since merge started 
.10:27:03.772 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [IFD][Lucene Merge Thread #0]: now checkpoint "_8m(5.5.1):C276" [1 segments ; isCommit = false] 
.10:27:03.772 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [IFD][Lucene Merge Thread #0]: 0 msec to checkpoint 
.10:27:03.772 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [IW][Lucene Merge Thread #0]: after commitMerge: _8m(5.5.1):C276 
.10:27:03.772 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [TMP][Lucene Merge Thread #0]: findMerges: 1 segments 
.10:27:03.772 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [TMP][Lucene Merge Thread #0]:   seg=_8m(5.5.1):C276 size=0.092 MB [floored] 
.10:27:03.772 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [TMP][Lucene Merge Thread #0]:   allowedSegmentCount=1 vs count=1 (eligible count=1) tooBigCount=0 
.10:27:03.772 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [IW][Lucene Merge Thread #0]: merge time 109 msec for 276 docs 
.10:27:03.772 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [MS][Lucene Merge Thread #0]:   merge thread: done 
.10:27:03.773 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [MS][Lucene Merge Thread #0]: now merge 
.10:27:03.773 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [MS][Lucene Merge Thread #0]:   index: _8m(5.5.1):C276 
.10:27:03.773 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [MS][Lucene Merge Thread #0]:   no more merges pending; now return 
.10:27:03.773 [Lucene Merge Thread #0] INFO  o.a.solr.update.LoggingInfoStream - [MS][Lucene Merge Thread #0]: updateMergeThreads ioThrottle=true targetMBPerSec=20.0 MB/sec 
.10:29:03.902 [pool-3-thread-1] INFO  o.a.h.i.c.SystemDefaultHttpClient - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://dbpedia.org:80: The target server failed to respond 
.10:29:03.905 [pool-3-thread-1] INFO  o.a.h.i.c.SystemDefaultHttpClient - Retrying request to {}->http://dbpedia.org:80 
.10:29:04.397 [http-nio-8080-exec-2] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Requesting GET for path tasks/a/result 
.10:29:04.405 [http-nio-8080-exec-2] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Response {
  "status" : 500,
  "text" : "uk.ac.shef.dcs.sti.STIException: uk.ac.shef.dcs.kbsearch.KBSearchException: HttpException: 500",
  "link" : null,
  "developerText" : "java.util.concurrent.ExecutionException: uk.ac.shef.dcs.sti.STIException: uk.ac.shef.dcs.kbsearch.KBSearchException: HttpException: 500\n\tat java.util.concurrent.FutureTask.report(FutureTask.java:122)\n\tat java.util.concurrent.FutureTask.get(FutureTask.java:192)\n\tat cz.cuni.mff.xrg.odalic.tasks.executions.FutureBasedExecutionService.getResultForTaskId(FutureBasedExecutionService.java:129)\n\tat cz.cuni.mff.xrg.odalic.api.rest.resources.ResultResource.getResult(ResultResource.java:46)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)\n\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)\n\tat org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:315)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:297)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:267)\n\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)\n\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)\n\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)\n\tat org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)\n\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)\n\tat org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)\n\tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: uk.ac.shef.dcs.sti.STIException: uk.ac.shef.dcs.kbsearch.KBSearchException: HttpException: 500\n\tat uk.ac.shef.dcs.sti.core.algorithm.tmp.TMPInterpreter.start(TMPInterpreter.java:106)\n\tat cz.cuni.mff.xrg.odalic.tasks.executions.FutureBasedExecutionService.lambda$submitForTaskId$0(FutureBasedExecutionService.java:110)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\t... 1 more\nCaused by: uk.ac.shef.dcs.kbsearch.KBSearchException: HttpException: 500\n\tat uk.ac.shef.dcs.kbsearch.sparql.SPARQLSearch.queryEntityCandidates(SPARQLSearch.java:284)\n\tat uk.ac.shef.dcs.kbsearch.sparql.SPARQLSearch.findEntityCandidatesOfTypes(SPARQLSearch.java:182)\n\tat uk.ac.shef.dcs.kbsearch.sparql.SPARQLSearch.findEntityCandidates(SPARQLSearch.java:170)\n\tat uk.ac.shef.dcs.sti.core.algorithm.tmp.LEARNINGPreliminaryColumnClassifier.runPreliminaryColumnClassifier(LEARNINGPreliminaryColumnClassifier.java:94)\n\tat uk.ac.shef.dcs.sti.core.algorithm.tmp.LEARNING.learn(LEARNING.java:27)\n\tat uk.ac.shef.dcs.sti.core.algorithm.tmp.TMPInterpreter.start(TMPInterpreter.java:84)\n\t... 5 more\nCaused by: HttpException: 500\n\tat org.apache.jena.sparql.engine.http.HttpQuery.rewrap(HttpQuery.java:411)\n\tat org.apache.jena.sparql.engine.http.HttpQuery.execGet(HttpQuery.java:355)\n\tat org.apache.jena.sparql.engine.http.HttpQuery.exec(HttpQuery.java:292)\n\tat org.apache.jena.sparql.engine.http.QueryEngineHTTP.execResultSetInner(QueryEngineHTTP.java:359)\n\tat org.apache.jena.sparql.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:351)\n\tat uk.ac.shef.dcs.kbsearch.sparql.SPARQLSearch.queryByLabel(SPARQLSearch.java:133)\n\tat uk.ac.shef.dcs.kbsearch.sparql.SPARQLSearch.queryEntityCandidates(SPARQLSearch.java:256)\n\t... 10 more\n"
```

This maybe connected with previous issues: 

```
.10:26:57.888 [coreLoadExecutor-6-thread-1] INFO  org.apache.solr.core.CoreContainer - Creating SolrCore 'websearch' using configuration from instancedir /Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/websearch 
.10:26:57.888 [coreLoadExecutor-6-thread-3] INFO  o.a.solr.handler.loader.XMLLoader - xsltCacheLifetimeSeconds=60 
.10:26:57.888 [coreLoadExecutor-6-thread-1] INFO  org.apache.solr.core.SolrCore - solr.NRTCachingDirectoryFactory 
.10:26:57.888 [coreLoadExecutor-6-thread-1] INFO  org.apache.solr.core.SolrCore - [[websearch] ] Opening new SolrCore at [/Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/websearch], dataDir=[/Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/websearch/data/] 
.10:26:57.888 [coreLoadExecutor-6-thread-1] INFO  org.apache.solr.core.JmxMonitoredMap - JMX monitoring is enabled. Adding Solr mbeans to JMX Server: com.sun.jmx.mbeanserver.JmxMBeanServer@59f95c5d 
.10:26:57.889 [coreLoadExecutor-6-thread-1] INFO  org.apache.solr.core.SolrCore - [[websearch] ] Added SolrEventListener for newSearcher: [org.apache.solr.core.QuerySenderListener{queries=[]}] 
.10:26:57.889 [coreLoadExecutor-6-thread-1] INFO  org.apache.solr.core.SolrCore - [[websearch] ] Added SolrEventListener for firstSearcher: [org.apache.solr.core.QuerySenderListener{queries=[{q=static firstSearcher warming in solrconfig.xml}]}] 
.10:26:57.889 [coreLoadExecutor-6-thread-1] INFO  o.a.solr.core.SchemaCodecFactory - Using default compressionMode: BEST_SPEED 
.10:26:57.889 [coreLoadExecutor-6-thread-1] INFO  o.a.s.core.CachingDirectoryFactory - return new directory for /Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/websearch/data 
.10:26:57.889 [coreLoadExecutor-6-thread-1] INFO  org.apache.solr.core.SolrCore - New index directory detected: old=null new=/Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/websearch/data/index/ 
.10:26:57.890 [coreLoadExecutor-6-thread-1] INFO  o.a.s.core.CachingDirectoryFactory - return new directory for /Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/websearch/data/index 
.10:26:57.890 [coreLoadExecutor-6-thread-1] INFO  org.apache.solr.core.PluginBag - queryResponseWriter : 'velocity' created with startup=lazy  
.10:26:57.890 [OldIndexDirectoryCleanupThreadForCore-websearch] INFO  org.apache.solr.core.SolrCore - Looking for old index directories to cleanup for core websearch in /Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/websearch/data/ 
.10:26:57.891 [coreLoadExecutor-6-thread-1] INFO  o.a.solr.response.XSLTResponseWriter - xsltCacheLifetimeSeconds=5 
.10:26:57.894 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.PluginBag - requestHandler : '/update/extract' created with startup=lazy  
.10:26:57.894 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.PluginBag - requestHandler : '/analysis/field' created with startup=lazy  
.10:26:57.894 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.PluginBag - requestHandler : '/analysis/document' created with startup=lazy  
.10:26:57.895 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.PluginBag - requestHandler : '/spell' created with startup=lazy  
.10:26:57.895 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.PluginBag - requestHandler : '/tvrh' created with startup=lazy  
.10:26:57.895 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.PluginBag - requestHandler : '/terms' created with startup=lazy  
.10:26:57.895 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.PluginBag - requestHandler : '/elevate' created with startup=lazy  
.10:26:57.895 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.RequestHandlers - Registered paths: /admin/mbeans,/browse,/update/json/docs,/admin/luke,/export,/get,/admin/properties,/elevate,/update/json,/admin/threads,/query,/analysis/field,/analysis/document,/spell,/update/csv,/tvrh,/select,/admin/segments,/admin/system,/replication,/config,/schema,/admin/plugins,/admin/logging,/admin,/admin/ping,/update,/admin/file,/debug/dump,/terms,/update/extract 
.10:26:57.896 [coreLoadExecutor-6-thread-1] INFO  org.apache.solr.core.SolrCore - no updateRequestProcessorChain defined as default, creating implicit default 
.10:26:57.897 [coreLoadExecutor-6-thread-1] INFO  o.a.solr.handler.loader.XMLLoader - xsltCacheLifetimeSeconds=60 
.10:26:57.898 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.SolrCore - Using default statsCache cache: org.apache.solr.search.stats.LocalStatsCache 
.10:26:57.898 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.update.UpdateHandler - Using UpdateLog implementation: org.apache.solr.update.UpdateLog 
.10:26:57.899 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.update.UpdateLog - Initializing UpdateLog: dataDir= defaultSyncLevel=FLUSH numRecordsToKeep=100 maxNumLogsToKeep=10 numVersionBuckets=65536 
.10:26:57.899 [coreLoadExecutor-6-thread-1] INFO  o.a.solr.handler.loader.XMLLoader - xsltCacheLifetimeSeconds=60 
.10:26:57.900 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.update.CommitTracker - Hard AutoCommit: if uncommited for 15000ms;  
.10:26:57.900 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.update.CommitTracker - Soft AutoCommit: disabled 
.10:26:57.900 [coreLoadExecutor-6-thread-1] INFO  o.a.solr.handler.loader.XMLLoader - xsltCacheLifetimeSeconds=60 
.10:26:57.901 [coreLoadExecutor-6-thread-3] INFO  o.a.solr.update.LoggingInfoStream - [IW][coreLoadExecutor-6-thread-3]: init: hit exception on init; releasing write lock 
.10:26:57.901 [coreLoadExecutor-6-thread-1] INFO  o.a.solr.handler.loader.XMLLoader - xsltCacheLifetimeSeconds=60 
.10:26:57.901 [coreLoadExecutor-6-thread-3] INFO  o.a.s.core.CachingDirectoryFactory - looking to close /Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/similarity/data/index [CachedDir<<refCount=0;path=/Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/similarity/data/index;done=true>>] 
.10:26:57.902 [coreLoadExecutor-6-thread-3] INFO  o.a.s.core.CachingDirectoryFactory - Closing directory: /Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/similarity/data/index 
.10:26:57.904 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.SolrCore - [similarity]  CLOSING SolrCore org.apache.solr.core.SolrCore@5849ca5b 
.10:26:57.904 [coreLoadExecutor-6-thread-3] INFO  o.a.solr.update.DirectUpdateHandler2 - closing DirectUpdateHandler2{commits=0,autocommit maxTime=15000ms,autocommits=0,soft autocommits=0,optimizes=0,rollbacks=0,expungeDeletes=0,docsPending=0,adds=0,deletesById=0,deletesByQuery=0,errors=0,cumulative_adds=0,cumulative_deletesById=0,cumulative_deletesByQuery=0,cumulative_errors=0,transaction_logs_total_size=0,transaction_logs_total_number=0} 
.10:26:57.904 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.update.SolrCoreState - Closing SolrCoreState 
.10:26:57.905 [coreLoadExecutor-6-thread-3] INFO  o.a.solr.update.DefaultSolrCoreState - SolrCoreState ref count has reached 0 - closing IndexWriter 
.10:26:57.905 [coreLoadExecutor-6-thread-3] INFO  o.a.solr.update.DefaultSolrCoreState - closing IndexWriter with IndexWriterCloser 
.10:26:57.905 [coreLoadExecutor-6-thread-3] INFO  org.apache.solr.core.SolrCore - [similarity] Closing main searcher on request. 
.10:26:57.907 [coreLoadExecutor-6-thread-3] INFO  o.a.s.core.CachingDirectoryFactory - Closing NRTCachingDirectoryFactory - 1 directories currently being tracked 
.10:26:57.907 [coreLoadExecutor-6-thread-3] INFO  o.a.s.core.CachingDirectoryFactory - looking to close /Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/similarity/data [CachedDir<<refCount=0;path=/Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/similarity/data;done=false>>] 
.10:26:57.907 [coreLoadExecutor-6-thread-3] INFO  o.a.s.core.CachingDirectoryFactory - Closing directory: /Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/similarity/data 
.10:26:57.914 [coreLoadExecutor-6-thread-3] ERROR org.apache.solr.core.CoreContainer - Error creating core [similarity]: Error opening new searcher 
org.apache.solr.common.SolrException: Error opening new searcher
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:820)
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:658)
    at org.apache.solr.core.CoreContainer.create(CoreContainer.java:814)
    at org.apache.solr.core.CoreContainer.access$000(CoreContainer.java:87)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:467)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:458)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor$1.run(ExecutorUtil.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
    at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:1676)
    at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1787)
    at org.apache.solr.core.SolrCore.initSearcher(SolrCore.java:914)
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:793)
    ... 10 common frames omitted
Caused by: org.apache.lucene.index.IndexNotFoundException: no segments* file found in LockValidatingDirectoryWrapper(NRTCachingDirectory(MMapDirectory@/Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/DBpedia/similarity/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@1caeb67c; maxCacheMB=48.0 maxMergeSizeMB=4.0)): files: [write.lock]
    at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:905)
    at org.apache.solr.update.SolrIndexWriter.<init>(SolrIndexWriter.java:78)
    at org.apache.solr.update.SolrIndexWriter.create(SolrIndexWriter.java:65)
    at org.apache.solr.update.DefaultSolrCoreState.createMainIndexWriter(DefaultSolrCoreState.java:237)
    at org.apache.solr.update.DefaultSolrCoreState.getIndexWriter(DefaultSolrCoreState.java:111)
    at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:1645)
    ... 13 common frames omitted
```

```
.10:27:00.505 [coreLoadExecutor-37-thread-3] INFO  o.a.solr.search.SolrIndexSearcher - Opening Searcher@71266550[relation] main 
.10:27:00.505 [coreLoadExecutor-37-thread-1] INFO  org.apache.solr.update.UpdateHandler - Using UpdateLog implementation: org.apache.solr.update.UpdateLog 
.10:27:00.729 [coreLoadExecutor-37-thread-1] INFO  org.apache.solr.update.UpdateLog - Initializing UpdateLog: dataDir= defaultSyncLevel=FLUSH numRecordsToKeep=100 maxNumLogsToKeep=10 numVersionBuckets=65536 
.10:27:00.730 [coreLoadExecutor-37-thread-3] INFO  o.a.solr.rest.ManagedResourceStorage - File-based storage initialized to use dir: /Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/German DBpedia/relation/conf 
.10:27:00.730 [coreLoadExecutor-37-thread-3] INFO  org.apache.solr.rest.RestManager - Initializing RestManager with initArgs: {storageDir=/Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/German DBpedia/relation/conf} 
.10:27:00.730 [coreLoadExecutor-37-thread-3] INFO  o.a.solr.rest.ManagedResourceStorage - Reading _rest_managed.json using file:dir=/Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/German DBpedia/relation/conf 
.10:27:00.730 [coreLoadExecutor-37-thread-3] INFO  org.apache.solr.rest.RestManager - Initializing 0 registered ManagedResources 
.10:27:00.731 [coreLoadExecutor-37-thread-1] INFO  org.apache.solr.update.CommitTracker - Hard AutoCommit: if uncommited for 15000ms;  
.10:27:00.731 [coreLoadExecutor-37-thread-1] INFO  org.apache.solr.update.CommitTracker - Soft AutoCommit: disabled 
.10:27:00.731 [coreLoadExecutor-37-thread-3] INFO  o.a.s.h.c.SpellCheckComponent - Initializing spell checkers 
.10:27:00.731 [coreLoadExecutor-37-thread-3] INFO  o.a.s.s.DirectSolrSpellChecker - init: {name=default,field=text,classname=solr.DirectSolrSpellChecker,distanceMeasure=internal,accuracy=0.5,maxEdits=2,minPrefix=1,maxInspections=5,minQueryLength=4,maxQueryFrequency=0.01} 
.10:27:00.731 [Finalizer] ERROR o.apache.solr.update.SolrIndexWriter - SolrIndexWriter was not closed prior to finalize(), indicates a bug -- POSSIBLE RESOURCE LEAK!!! 
.10:27:00.731 [coreLoadExecutor-37-thread-3] INFO  o.a.s.h.c.SpellCheckComponent - No queryConverter defined, using default converter 
.10:27:00.731 [Finalizer] INFO  o.a.solr.update.LoggingInfoStream - [IW][Finalizer]: now flush at close 
.10:27:00.732 [Finalizer] INFO  o.a.solr.update.LoggingInfoStream - [IW][Finalizer]:   start flush: applyAllDeletes=true 
.10:27:00.732 [coreLoadExecutor-37-thread-3] INFO  o.a.s.h.c.QueryElevationComponent - Loading QueryElevation from: /Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/German DBpedia/relation/conf/elevate.xml 
.10:27:00.732 [Finalizer] INFO  o.a.solr.update.LoggingInfoStream - [IW][Finalizer]: hit exception during flush 
.10:27:00.732 [Finalizer] INFO  o.a.solr.update.LoggingInfoStream - [IW][Finalizer]: rollback 
.10:27:00.732 [Finalizer] INFO  o.a.solr.update.LoggingInfoStream - [IW][Finalizer]: all running merges have aborted 
.10:27:00.732 [Finalizer] INFO  o.a.solr.update.LoggingInfoStream - [IW][Finalizer]: rollback: done finish merges 
.10:27:00.732 [Finalizer] ERROR o.apache.solr.update.SolrIndexWriter - Error closing IndexWriter 
java.lang.NullPointerException: null
    at org.apache.lucene.index.IndexWriter.segString(IndexWriter.java:4278)
    at org.apache.lucene.index.IndexWriter.segString(IndexWriter.java:4269)
    at org.apache.lucene.index.IndexWriter.doFlush(IndexWriter.java:3105)
    at org.apache.lucene.index.IndexWriter.flush(IndexWriter.java:3087)
    at org.apache.lucene.index.IndexWriter.shutdown(IndexWriter.java:1080)
    at org.apache.lucene.index.IndexWriter.close(IndexWriter.java:1125)
    at org.apache.solr.update.SolrIndexWriter.close(SolrIndexWriter.java:130)
    at org.apache.solr.update.SolrIndexWriter.finalize(SolrIndexWriter.java:183)
    at java.lang.System$2.invokeFinalize(System.java:1270)
    at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
    at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
    at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)
.10:27:00.732 [coreLoadExecutor-37-thread-1] INFO  o.a.solr.update.LoggingInfoStream - [IFD][coreLoadExecutor-37-thread-1]: init: current segments file is "segments_1"; deletionPolicy=org.apache.solr.core.IndexDeletionPolicyWrapper@667ea182 
.10:27:00.732 [coreLoadExecutor-37-thread-1] INFO  o.a.solr.update.LoggingInfoStream - [IFD][coreLoadExecutor-37-thread-1]: init: load commit "segments_1" 
.10:27:00.733 [coreLoadExecutor-37-thread-1] INFO  o.a.solr.core.SolrDeletionPolicy - SolrDeletionPolicy.onInit: commits: num=1
    commit{dir=NRTCachingDirectory(MMapDirectory@/Users/tomasknap/Documents/PROJECTS/Odalic/sti/cache/German DBpedia/class/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@1caeb67c; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_1,generation=1} 
.10:27:00.733 [coreLoadExecutor-37-thread-1] INFO  o.a.solr.core.SolrDeletionPolicy - newest commit generation = 1 
.10:27:00.733 [coreLoadExecutor-37-thread-1] INFO  o.a.solr.update.LoggingInfoStream - [IFD][coreLoadExecutor-37-thread-1]: now checkpoint "" [0 segments ; isCommit = false] 
.10:27:00.733 [coreLoadExecutor-37-thread-1] INFO  o.a.solr.update.LoggingInfoStream - [IFD][coreLoadExecutor-37-thread-1]: 0 msec to checkpoint 
.10:27:00.733 [coreLoadExecutor-37-thread-1] INFO  o.a.solr.update.LoggingInfoStream - [IW][coreLoadExecutor-37-thread-1]: init: create=false 
.10:27:00.733 [coreLoadExecutor-37-thread-1] INFO  o.a.solr.update.LoggingInfoStream - [IW][coreLoadExecutor-37-thread-1]: 
```

**Comment by brodecva** [comment]
@tomas-knap This may be related to #135 . Assigning to @JanVana .

**Comment by tomas-knap** [comment]
Tested now, working
