### ISSUE TITLE
Cannot download task configuration

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#370]
Steps: 
1) Define a task, e.g. with Book-v1
2) Click "Download task configuration".  (before or after execution)

As a result, I got an error. 

.17:02:26.302 [http-nio-8080-exec-8] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Requesting GET for path tasks/Books 
.17:03:05.913 [http-nio-8080-exec-1] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Requesting OPTIONS for path tasks/Books 
.17:03:05.913 [http-nio-8080-exec-1] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Reply "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/Pgo8YXBwbGljYXRpb24geG1sbnM9Imh0dHA6Ly93YWRsLmRldi5qYXZhLm5ldC8yMDA5LzAyIj4KICAgIDxkb2MgeG1sbnM6amVyc2V5PSJodHRwOi8vamVyc2V5LmphdmEubmV0LyIgamVyc2V5OmdlbmVyYXRlZEJ5PSJKZXJzZXk6IDIuMjMuMSAyMDE2LTA2LTA5IDE4OjA1OjQ3Ii8+CiAgICA8Z3JhbW1hcnM+CiAgICAgICAgPGluY2x1ZGUgaHJlZj0iaHR0cDovL2xvY2FsaG9zdDo4MDgwL29kYWxpYy9hcHBsaWNhdGlvbi53YWRsL3hzZDAueHNkIj4KICAgICAgICAgICAgPGRvYyB0aXRsZT0iR2VuZXJhdGVkIiB4bWw6bGFuZz0iZW4iLz4KICAgICAgICA8L2luY2x1ZGU+CiAgICA8L2dyYW1tYXJzPgogICAgPHJlc291cmNlcyBiYXNlPSJodHRwOi8vbG9jYWxob3N0OjgwODAvb2RhbGljLyI+CiAgICAgICAgPHJlc291cmNlIHBhdGg9InRhc2tzL0Jvb2tzIj4KICAgICAgICAgICAgPG1ldGhvZCBpZD0iZ2V0VGFza0J5SWQiIG5hbWU9IkdFVCI+CiAgICAgICAgICAgICAgICA8cmVzcG9uc2U+CiAgICAgICAgICAgICAgICAgICAgPHJlcHJlc2VudGF0aW9uIG1lZGlhVHlwZT0iYXBwbGljYXRpb24vanNvbiIvPgogICAgICAgICAgICAgICAgPC9yZXNwb25zZT4KICAgICAgICAgICAgPC9tZXRob2Q+CiAgICAgICAgICAgIDxtZXRob2QgaWQ9InB1dFRhc2tXaXRoSWQiIG5hbWU9IlBVVCI+CiAgICAgICAgICAgICAgICA8cmVxdWVzdD4KICAgICAgICAgICAgICAgICAgICA8bnMyOnJlcHJlc2VudGF0aW9uIHhtbG5zOm5zMj0iaHR0cDovL3dhZGwuZGV2LmphdmEubmV0LzIwMDkvMDIiIHhtbG5zPSIiIGVsZW1lbnQ9InRhc2siIG1lZGlhVHlwZT0iYXBwbGljYXRpb24vanNvbiIvPgogICAgICAgICAgICAgICAgPC9yZXF1ZXN0PgogICAgICAgICAgICAgICAgPHJlc3BvbnNlPgogICAgICAgICAgICAgICAgICAgIDxyZXByZXNlbnRhdGlvbiBtZWRpYVR5cGU9ImFwcGxpY2F0aW9uL2pzb24iLz4KICAgICAgICAgICAgICAgIDwvcmVzcG9uc2U+CiAgICAgICAgICAgIDwvbWV0aG9kPgogICAgICAgICAgICA8bWV0aG9kIGlkPSJkZWxldGVUYXNrQnlJZCIgbmFtZT0iREVMRVRFIj4KICAgICAgICAgICAgICAgIDxyZXNwb25zZT4KICAgICAgICAgICAgICAgICAgICA8cmVwcmVzZW50YXRpb24gbWVkaWFUeXBlPSJhcHBsaWNhdGlvbi9qc29uIi8+CiAgICAgICAgICAgICAgICA8L3Jlc3BvbnNlPgogICAgICAgICAgICA8L21ldGhvZD4KICAgICAgICAgICAgPG1ldGhvZCBpZD0iaW1wb3J0VGFza0lkIiBuYW1lPSJQVVQiPgogICAgICAgICAgICAgICAgPHJlcXVlc3Q+CiAgICAgICAgICAgICAgICAgICAgPHJlcHJlc2VudGF0aW9uIG1lZGlhVHlwZT0idGV4dC90dXJ0bGUiLz4KICAgICAgICAgICAgICAgIDwvcmVxdWVzdD4KICAgICAgICAgICAgICAgIDxyZXNwb25zZT4KICAgICAgICAgICAgICAgICAgICA8cmVwcmVzZW50YXRpb24gbWVkaWFUeXBlPSJhcHBsaWNhdGlvbi9qc29uIi8+CiAgICAgICAgICAgICAgICA8L3Jlc3BvbnNlPgogICAgICAgICAgICA8L21ldGhvZD4KICAgICAgICA8L3Jlc291cmNlPgogICAgPC9yZXNvdXJjZXM+CjwvYXBwbGljYXRpb24+Cg==" 
.17:03:05.938 [http-nio-8080-exec-10] WARN  c.c.m.x.o.a.r.r.ThrowableMapper - Mapping of throwable Did not recognise RDF format object Turtle (mimeTypes=text/turtle, application/x-turtle; ext=ttl) 
org.openrdf.rio.UnsupportedRDFormatException: Did not recognise RDF format object Turtle (mimeTypes=text/turtle, application/x-turtle; ext=ttl)
	at org.openrdf.rio.Rio.lambda$unsupportedFormat$0(Rio.java:630)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.openrdf.rio.Rio.createWriter(Rio.java:172)
	at org.openrdf.rio.Rio.write(Rio.java:447)
	at org.openrdf.rio.Rio.write(Rio.java:389)
	at cz.cuni.mff.xrg.odalic.api.rdf.TurtleRdfMappingTaskSerializationService.format(TurtleRdfMappingTaskSerializationService.java:93)
	at cz.cuni.mff.xrg.odalic.api.rdf.TurtleRdfMappingTaskSerializationService.serialize(TurtleRdfMappingTaskSerializationService.java:83)
	at cz.cuni.mff.xrg.odalic.api.rest.resources.TasksResource.exportTaskId(TasksResource.java:326)
	at cz.cuni.mff.xrg.odalic.api.rest.resources.TasksResource.exportTaskId(TasksResource.java:335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:106)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
.17:03:05.939 [http-nio-8080-exec-10] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Requesting GET for path tasks/Books

**Comment by brodecva** [comment]
@tomas-knap Hm, works for me. Maybe there is some clash of dependencies. I will try to make the dependencies as explicit as possible.

**Comment by brodecva** [comment]
@tomas-knap Hi, I made all Pinto the dependencies runtime required, please try again. For me and Ištván, there are no problems.

**Comment by tomas-knap** [comment]
Works
