### ISSUE TITLE
Cannot process one of the testing files - it was working before!

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#372]
Please set up knowledge base as defined at: 
https://grips.semantic-web.at/display/ADEQ/Odalic+-+Connection+to+the+Knowledge+Base

Use file: 
[STMK_2012_LIVEBIRTHS-10lines.csv.zip](https://github.com/odalic/sti/files/776542/STMK_2012_LIVEBIRTHS-10lines.csv.zip)

Cannot further process that file: but it was working before (approx 2 weeks back)

The problematic query
```
SELECT DISTINCT  ?subject
WHERE
  { ?subject  <http://www.w3.org/2004/02/skos/core#prefLabel>  "Gro� Sankt Florian"@de ;
              a                     <http://www.w3.org/2004/02/skos/core#Concept>
  }

```

I guess that there may be an issue with that special char?

The log:
```
java.util.concurrent.ExecutionException: javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created at java.util.concurrent.FutureTask.report(FutureTask.java:122) at java.util.concurrent.FutureTask.get(FutureTask.java:192) at cz.cuni.mff.xrg.odalic.tasks.executions.DbCachedFutureBasedExecutionService.getResultForTaskId(DbCachedFutureBasedExecutionService.java:227) at cz.cuni.mff.xrg.odalic.api.rest.resources.ResultResource.getResult(ResultResource.java:63) at cz.cuni.mff.xrg.odalic.api.rest.resources.ResultResource.getResult(ResultResource.java:78) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) at org.glassfish.jersey.internal.Errors.process(Errors.java:315) at org.glassfish.jersey.internal.Errors.process(Errors.java:297) at org.glassfish.jersey.internal.Errors.process(Errors.java:267) at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:106) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745) Caused by: javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:370) at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:313) at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:227) at javax.xml.stream.XMLInputFactory.newInstance(XMLInputFactory.java:154) at org.apache.jena.sparql.resultset.XMLInputStAX.<init>(XMLInputStAX.java:101) at org.apache.jena.sparql.resultset.XMLInput.make(XMLInput.java:74) at org.apache.jena.sparql.resultset.XMLInput.fromXML(XMLInput.java:38) at org.apache.jena.sparql.resultset.XMLInput.fromXML(XMLInput.java:34) at org.apache.jena.query.ResultSetFactory.fromXML(ResultSetFactory.java:308) at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execResultSetInner(QueryEngineHTTP.java:365) at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:334) at uk.ac.shef.dcs.kbproxy.sparql.SPARQLProxy.queryReturnSingleValues(SPARQLProxy.java:228) at uk.ac.shef.dcs.kbproxy.sparql.SPARQLProxy.queryReturnSingleValues(SPARQLProxy.java:219) at uk.ac.shef.dcs.kbproxy.sparql.SPARQLProxy.queryEntityCandidates(SPARQLProxy.java:631) at uk.ac.shef.dcs.kbproxy.sparql.SPARQLProxy.findEntityCandidatesInternal(SPARQLProxy.java:364) at uk.ac.shef.dcs.kbproxy.KBProxy.lambda$findEntityCandidates$0(KBProxy.java:144) at uk.ac.shef.dcs.kbproxy.KBProxy.Do(KBProxy.java:387) at uk.ac.shef.dcs.kbproxy.KBProxy.findEntityCandidates(KBProxy.java:144) at uk.ac.shef.dcs.sti.core.algorithm.tmp.LEARNINGPreliminaryColumnClassifier.runPreliminaryColumnClassifier(LEARNINGPreliminaryColumnClassifier.java:120) at uk.ac.shef.dcs.sti.core.algorithm.tmp.LEARNING.learn(LEARNING.java:37) at uk.ac.shef.dcs.sti.core.algorithm.tmp.TMPOdalicInterpreter.start(TMPOdalicInterpreter.java:114) at cz.cuni.mff.xrg.odalic.tasks.executions.DbCachedFutureBasedExecutionService.lambda$submitForTaskId$29(DbCachedFutureBasedExecutionService.java:160) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ... 1 more Caused by: java.lang.RuntimeException: Provider for class javax.xml.stream.XMLInputFactory cannot be created at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:367) ... 25 more Caused by: java.util.ServiceConfigurationError: javax.xml.stream.XMLInputFactory: Error reading configuration file at java.util.ServiceLoader.fail(ServiceLoader.java:232) at java.util.ServiceLoader.parse(ServiceLoader.java:309) at java.util.ServiceLoader.access$200(ServiceLoader.java:185) at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357) at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393) at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474) at javax.xml.stream.FactoryFinder$1.run(FactoryFinder.java:352) at java.security.AccessController.doPrivileged(Native Method) at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:341) ... 25 more Caused by: java.io.FileNotFoundException: /usr/local/apache-tomcat-8.0.36/webapps/odalic/WEB-INF/lib/woodstox-core-asl-4.4.1.jar (No such file or directory) at java.util.zip.ZipFile.open(Native Method) at java.util.zip.ZipFile.<init>(ZipFile.java:219) at java.util.zip.ZipFile.<init>(ZipFile.java:149) at java.util.jar.JarFile.<init>(JarFile.java:166) at java.util.jar.JarFile.<init>(JarFile.java:103) at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93) at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69) at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99) at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122) at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150) at java.net.URL.openStream(URL.java:1038) at java.util.ServiceLoader.parse(ServiceLoader.java:304) ... 32 more 

```

This also means that #166 does not work properly??

**Comment by tomas-knap** [comment]
Strange, cannot reproduce now. I am a bit confused ;-) 

Btw. Is it ok to suppres warnings e.g.: SPARQLProxy, 591, 707?

**Comment by tomas-knap** [comment]
Closing for now as I cannot reproduce :(
