### ISSUE TITLE
Cannot run books-v1 cvs with two KBs, getting error 502

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#443]
Run Books-v1.csv with Dbpedia Jan and German Dbpedia. It ends with error: 
![screen shot 2017-05-23 at 16 59 53](https://cloud.githubusercontent.com/assets/3014917/26360804/618b0016-3fd9-11e7-8594-98c92046e4f9.png)

```
java.util.concurrent.ExecutionException: HttpException: 502 at java.util.concurrent.FutureTask.report(FutureTask.java:122) at java.util.concurrent.FutureTask.get(FutureTask.java:192) at cz.cuni.mff.xrg.odalic.tasks.executions.DbCachedFutureBasedExecutionService.getResultForTaskId(DbCachedFutureBasedExecutionService.java:150) at cz.cuni.mff.xrg.odalic.api.rest.resources.ResultResource.getResult(ResultResource.java:73) at cz.cuni.mff.xrg.odalic.api.rest.resources.ResultResource.getResult(ResultResource.java:60) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) at org.glassfish.jersey.internal.Errors.process(Errors.java:315) at org.glassfish.jersey.internal.Errors.process(Errors.java:297) at org.glassfish.jersey.internal.Errors.process(Errors.java:267) at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745) Caused by: HttpException: 502 at org.apache.jena.sparql.engine.http.HttpQuery.rewrap(HttpQuery.java:368) at org.apache.jena.sparql.engine.http.HttpQuery.execPost(HttpQuery.java:356) at org.apache.jena.sparql.engine.http.HttpQuery.exec(HttpQuery.java:281) at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execAsk(QueryEngineHTTP.java:484) at uk.ac.shef.dcs.kbproxy.sparql.SparqlProxyCore.ask(SparqlProxyCore.java:262) at uk.ac.shef.dcs.kbproxy.sparql.SparqlProxyCore.filterStructurePredicates(SparqlProxyCore.java:904) at uk.ac.shef.dcs.kbproxy.sparql.SparqlProxyCore.filterStructurePredicates(SparqlProxyCore.java:894) at uk.ac.shef.dcs.kbproxy.sparql.SparqlProxyCore.<init>(SparqlProxyCore.java:130) at uk.ac.shef.dcs.kbproxy.sparql.SparqlProxyCore.<init>(SparqlProxyCore.java:101) at uk.ac.shef.dcs.kbproxy.sparql.SparqlProxyCoreFactory.create(SparqlProxyCoreFactory.java:17) at uk.ac.shef.dcs.kbproxy.DefaultProxiesFactory.create(DefaultProxiesFactory.java:53) at cz.cuni.mff.xrg.odalic.bases.proxies.MemoryOnlyKnowledgeBaseProxiesService.toProxies(MemoryOnlyKnowledgeBaseProxiesService.java:55) at cz.cuni.mff.xrg.odalic.tasks.executions.TableMinerPlusFactory.initializeInterpreters(TableMinerPlusFactory.java:141) at cz.cuni.mff.xrg.odalic.tasks.executions.TableMinerPlusFactory.getInterpreters(TableMinerPlusFactory.java:108) at cz.cuni.mff.xrg.odalic.tasks.executions.DbCachedFutureBasedExecutionService.lambda$submitForTaskId$0(DbCachedFutureBasedExecutionService.java:282) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ... 1 more 
```

This should not happen at all!

**Comment by tomas-knap** [comment]
Can you reproduce?

**Comment by brodecva** [comment]
Yeah, the German DBpedia is down. But the error message could be definitely improved. I will look into it, my work on the user-friendly messages is not done yet...

**Comment by tomas-knap** [comment]
Ok, thanks!

**Comment by tomas-knap** [comment]
This is quite important, because if that happens to oponent, he will not be happy - and this issue was already pointed out in March

**Comment by brodecva** [comment]
As of https://github.com/odalic/sti/commit/46f538a1450a36f34c65d41dc75e42325221a5b6 , the server reports in more clear way that the error was caused by a query to the specific proxy. Not sure what else can be done about that, the particular exception returned and its message is provided by underlying Jena library and may depend on particular situation. In this case it was the German DBpedia endpoint or rather the HTTP library Jena uses, that returned the HTTP 502 error. Which slightly masked the true reason of the error: that the endpoint was unresponsive.
