### ISSUE TITLE
WSScorer issues when bing key is not valid anymore

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#473]
KBs: Dbpedia-Jan (but probably also other KBs)
File:
version 1.1.2-SNAPSHOT

Steps: 
1) Create a task with the given kb/file, run it, 
2) As a result you get

```
javax.ws.rs.InternalServerErrorException: java.lang.NullPointerException at cz.cuni.mff.xrg.odalic.api.rest.resources.ResultResource.getResult(ResultResource.java:83) at cz.cuni.mff.xrg.odalic.api.rest.resources.ResultResource.getResult(ResultResource.java:61) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) at org.glassfish.jersey.internal.Errors.process(Errors.java:315) at org.glassfish.jersey.internal.Errors.process(Errors.java:297) at org.glassfish.jersey.internal.Errors.process(Errors.java:267) at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748) Caused by: uk.ac.shef.dcs.sti.STIException: java.lang.NullPointerException at uk.ac.shef.dcs.sti.core.algorithm.tmp.TMPOdalicInterpreter.start(TMPOdalicInterpreter.java:231) at cz.cuni.mff.xrg.odalic.tasks.executions.DbCachedFutureBasedExecutionService.lambda$submitForTaskId$1(DbCachedFutureBasedExecutionService.java:331) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ... 1 more Caused by: java.lang.NullPointerException at uk.ac.shef.dcs.sti.core.subjectcol.WSScorer.score(WSScorer.java:111) at uk.ac.shef.dcs.sti.core.subjectcol.WSScorer.score(WSScorer.java:326) at uk.ac.shef.dcs.sti.core.subjectcol.TColumnFeatureGenerator.setWSScores(TColumnFeatureGenerator.java:434) at uk.ac.shef.dcs.sti.core.subjectcol.SubjectColumnDetector.computeWSScores(SubjectColumnDetector.java:220) at uk.ac.shef.dcs.sti.core.subjectcol.SubjectColumnDetector.compute(SubjectColumnDetector.java:186) at uk.ac.shef.dcs.sti.core.algorithm.tmp.TMPOdalicInterpreter.start(TMPOdalicInterpreter.java:173) ... 5 more 
```

Root cause is probably:
```
java.lang.NullPointerException at uk.ac.shef.dcs.sti.core.subjectcol.WSScorer.score(WSScorer.java:111) at 
```

Which points to line : 

```
for (final WebSearchResultDoc doc : searchResult) 
```

**Comment by tomas-knap** [comment]
Caused by expired bing API key.

**Comment by tomas-knap** [comment]
Message should be improved

**Comment by tomas-knap** [comment]
Closing as bing is not needed in default settings
